# Generated by Django 5.0.4 on 2024-04-17 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter the author's first name", max_length=100, validators=[django.core.validators.RegexValidator(message='Names must contain only letters,\n        spaces, commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, help_text="Enter the author's middle name or initial", max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Names must contain only letters,\n        spaces, commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='Middle Name')),
                ('last_name', models.CharField(help_text="Enter the author's last name", max_length=100, validators=[django.core.validators.RegexValidator(message='Names must contain only letters,\n        spaces, commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='Last Name')),
            ],
        ),
    ]
