# Generated by Django 5.0.4 on 2024-05-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(help_text='A URL-friendly name is entered automatically on save', max_length=255, unique=True),
        ),
    ]
