# Generated by Django 5.0.4 on 2024-04-17 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0002_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the book', max_length=255, verbose_name='Book Title')),
                ('slug', models.SlugField(blank=True, help_text='Enter a URL-friendly name', unique=True)),
                ('publication_year', models.IntegerField(help_text='Enter the year the book was published', verbose_name='Publication Year')),
                ('isbn', models.CharField(help_text='Enter the ISBN number of the book', max_length=13, unique=True, verbose_name='ISBN')),
                ('added_at', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('genre', models.ForeignKey(help_text='Select the genre of the book', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='scroll_core.genre')),
                ('user', models.ForeignKey(help_text='Select the owner of the book', on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
