# Generated by Django 5.0.4 on 2024-05-10 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0003_alter_book_isbn_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text="Enter the author's first name", max_length=100, validators=[django.core.validators.RegexValidator(message='Names must contain only letters, spaces,commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text="Enter the author's last name", max_length=100, validators=[django.core.validators.RegexValidator(message='Names must contain only letters, spaces,commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, help_text="Optional: Enter the author's middle name or initial", max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Names must contain only letters, spaces,commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='Enter the ISBN no. of the book, 10 or 13 digits & hyphens', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must only contain numbers and hyphens.', regex='^[\\d-]+$')], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, help_text='Enter the year the book was published', null=True, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1000)], verbose_name='Publication Year'),
        ),
    ]
