# Generated by Django 5.0.4 on 2024-04-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(help_text='Select the author associated with a book', on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='scroll_core.author')),
                ('book', models.ForeignKey(help_text='Select the book associated with an author', on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='scroll_core.book')),
            ],
        ),
    ]
