# Generated by Django 5.0.4 on 2024-04-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0005_alter_book_isbn_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', verbose_name='Description'),
        ),
    ]
