# Generated by Django 5.0.4 on 2024-04-25 07:33

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0006_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, help_text='Enter a brief description of the book', verbose_name='Description'),
        ),
    ]
