# Generated by Django 5.0.4 on 2024-11-02 11:08

import django.core.validators
import django.db.models.deletion
import djrichtextfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0006_alter_book_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Names must contain only letters, spaces,commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Names must contain only letters, spaces,commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Names must contain only letters, spaces,commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must only contain numbers and hyphens.', regex='^[\\d-]+$')], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1000)], verbose_name='Publication Year'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Book Title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='scroll_core.author'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='scroll_core.book'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Genre Name'),
        ),
    ]
