# Generated by Django 5.0.4 on 2024-04-25 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0007_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='Enter the ISBN number of the book', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must only contain numbers and hyphens.', regex='^[\\d-]+$')], verbose_name='ISBN'),
        ),
    ]
