# Generated by Django 5.0.4 on 2024-04-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0008_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Added'),
        ),
    ]
