# Generated by Django 5.0.4 on 2024-04-27 09:02

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0010_book_image_book_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[400, None], upload_to='scroll_core/'),
        ),
    ]
