# Generated by Django 5.0.4 on 2024-04-28 20:25

import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0013_alter_book_options_alter_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text="Enter the author's first name", max_length=100, validators=[django.core.validators.RegexValidator(message='Names must contain only letters, spaces, commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text="Enter the author's last name", max_length=100, validators=[django.core.validators.RegexValidator(message='Names must contain only letters, spaces, commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, help_text="Optional: Enter the author's middle name or initial", max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Names must contain only letters, spaces, commas, periods, or hyphens.', regex='^[a-zA-Z,.\\s-]+$')], verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/default-book-200.webp', force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[400, None], upload_to='images/'),
        ),
    ]
