# Generated by Django 5.0.4 on 2024-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0014_alter_book_options_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='book',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Deleted'),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Updated'),
        ),
    ]
