# Generated by Django 5.0.4 on 2024-04-29 12:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0015_alter_book_options_book_deleted_at_book_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://asset.cloudinary.com/dsbcjtatz/ddeba64fcd3d98104e7c29d4f2a66e5d', max_length=255, verbose_name='image'),
        ),
    ]
