# Generated by Django 5.0.4 on 2024-05-01 17:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0019_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dsbcjtatz/image/upload/v1714578907/scroll_core/book_cover_images/default-book-cover_t2lyio.webp', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dsbcjtatz/image/upload/v1714579934/scroll_core/user_profile_image/default-profile-image_qscipu.webp', max_length=255, verbose_name='image'),
        ),
    ]
