# Generated by Django 5.0.4 on 2024-05-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroll_core', '0020_alter_book_image_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(help_text='A URL-friendly name is entered automatically on save'),
        ),
    ]
